config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('files.urls', namespace='files')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path

from files.apps import FilesConfig
from files.views import UploadCreateView, UploadListView, UploadDetailView, UploadDeleteView

app_name = FilesConfig.name
urlpatterns = [
    path('upload/', UploadCreateView.as_view(template_name='files/upload_form.html'), name='upload'),
    path('', UploadListView.as_view(template_name='files/upload_list.html'), name='upload_list'),
    path('<int:pk>/', UploadDetailView.as_view(template_name='files/upload_detail.html'), name='upload_detail'),
    path('delete/<int:pk>/', UploadDeleteView.as_view(), name='upload_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

files/models.py
from django.db import models

from users.models import User, NULLABLE


class File(models.Model):
    '''Модель для загружаемого файла с полями пользователя, который загрузил файл, самим файлом и датой загрузки'''
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='пользователь', **NULLABLE)
    upload_file = models.FileField(upload_to='files')
    upload_date = models.DateTimeField(auto_now_add=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    '''Модель пользователя с переопределенным username на почту и полями ФИО, почта и блокировка пользователя'''
    username = None

    full_name = models.CharField(max_length=255, verbose_name='ФИО', **NULLABLE)
    email = models.EmailField(max_length=254, unique=True, verbose_name='email')
    is_active = models.BooleanField(default=True, verbose_name='активный')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    '''Форма для регистрации пользователя'''
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(UserChangeForm):
    '''Форма для просмотра и изменения данных пользователя'''
    class Meta:
        model = User
        fields = ('email', 'full_name',)

    def __init__(self, *args, **kwargs):
        forms.ModelForm.__init__(self, *args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

files/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.views import generic

from .models import File


class UploadCreateView(LoginRequiredMixin, generic.CreateView):
    '''Контроллер для загрузки файла'''
    model = File
    fields = ['upload_file', ]
    success_url = reverse_lazy('files:upload_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['documents'] = File.objects.all()
        return context


class UploadListView(generic.ListView):
    '''Контроллер для просмотра списка файлов постранично по 3 файла на страницу'''
    model = File
    paginate_by = 3

    def get_queryset(self):
        '''Функция для получения набора обьектов из базы данных, в которой определяются 2 дополнительных поля с колонками и названием'''
        queryset = super().get_queryset()
        for i in queryset:
            file = str(i.upload_file)
            i.name = file[6:]
            with open("media/" + file, 'r', encoding='utf-8') as csv_file:
                li = list(csv.DictReader(csv_file))
                headers = ", ".join(li[0].keys())
            i.headers = headers
        return queryset


class UploadDetailView(LoginRequiredMixin, generic.DetailView):
    '''Контроллер для просмотра содержимого файла'''
    model = File

    def get_object(self):
        obj = super().get_object()
        with open("media/" + obj.upload_file.name, 'r', encoding='utf-8') as csv_file:
            li = list(csv.DictReader(csv_file))
            obj.li = li
            headers = li[0].keys()
            obj.headers = headers
            obj.save()
        return obj


class UploadDeleteView(generic.DeleteView):
    '''Контроллер для удаления файла'''
    model = File
    success_url = reverse_lazy('files:upload_list')

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    """Контроллер для регистрации пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})


class ProfileView(UpdateView):
    """Контроллер для просмотра и изменения данных пользователя"""
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

files/templates/files/base.html
{%load static%}

<!doctype html>
<html lang="ru" data-bs-theme="auto"   <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Пример на bootstrap 5: Продукт - продвигающая маркетинговая страница · Версия v5.3.0-alpha3">
	<title>Продукт | Product example for Bootstrap · Версия v5.3.0-alpha3</title>

	<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">



<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>


{% include 'files/includes/inc_main_menu.html' %}

{% block content %}

{% endblock %}


<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <small class="d-block mb-3 text-body-secondary">&copy; 2023–{% now 'Y' %}</small>
  </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.js/bootstrap.bundle.min.js' %}" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


  </body>
</html>

files/templates/files/file_confirm_delete.html
{% extends 'files/base.html' %}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
<form method="post">
      {%csrf_token%}
      Подтверждаете удаление файла?
      <input type="submit" class="btn btn-outline-danger" value="Подтвердить">
</form>
{% endblock %}

files/templates/files/includes/inc_main_menu.html
<header class="site-header sticky-top py-1">
  <nav class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="#" aria-label="Product">
    </a>
    <a class="py-2 d-none d-md-inline-block" href="{%url 'files:upload_list' %}">Главная</a>
    <a class="py-2 d-none d-md-inline-block" href="{%url 'files:upload' %}">Загрузить файл</a>
    {% if user.is_authenticated %}
      <a class="py-2 d-none d-md-inline-block" href="{%url 'users:profile' %}">Профиль</a>
      <a class="py-2 d-none d-md-inline-block" href="{%url 'users:logout' %}">Выйти</a>
    {% else %}
      <a class="py-2 d-none d-md-inline-block" href="{%url 'users:login' %}">Войти</a>
      <a class="py-2 d-none d-md-inline-block" href="{%url 'users:register' %}">Регистрация</a>
    {% endif %}
  </nav>
</header>

files/templates/files/includes/pagination.html
<div>
  <span>
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

files/templates/files/upload_detail.html
{% extends 'files/base.html' %}
{%load static%}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
<div style="padding:40px;margin:40px;border:1px solid #ccc">
    <table id="myTable" class="display">
        <thead>
            <tr>
            {% for header in file.headers %}
                <th>{{ header }}</th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in file.li %}
            <tr>
                {% for val in row.values %}
                    <td>{{ val }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
</div>
{% endblock %}

files/templates/files/upload_form.html
{% extends 'files/base.html' %}
{%load static%}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
<div style="padding:40px;margin:40px;border:1px solid #ccc">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form><hr>
    <ul>
    {% for file in files %}
        <li>
            <a href="{{ file.upload_file.url }}">{{ file.upload_file.name }}</a>
            <small>({{ file.upload_file.size|filesizeformat }}) - {{file.upload_date}}</small>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

files/templates/files/upload_list.html
{% extends 'files/base.html' %}
{%load static%}

{% block content %}
<main>

<div style="padding:40px;margin:40px;border:1px solid #ccc">
    <ul>
    {% for object in object_list %}
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-4 fw-normal">{{object.name}}</h1>
      <p><b>Колонки:</b></p>
      <p>{{object.headers}}</p>
      <a class="btn btn-outline-secondary" href="{%url 'files:upload_detail' pk=object.pk%}">Посмотреть содержимое</a>
      <a class="btn btn-outline-danger" href="{%url 'files:upload_delete' pk=object.pk %}">Удалить</a>
    </div>
    {% endfor %}
    </ul>
</div>
{% include "files/includes/pagination.html" %}
{% endblock %}

users/templates/users/login.html
{% extends 'files/base.html' %}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
      <div class="col-6">
            <form method="post" enctype=multipart/form-data>
            <div class="card">
                  <div class="card-header">
                        Вход
                  </div>
                  <div class="card-body">
                        <form method="post">
                              {%csrf_token%}
                              {{form.as_p}}
                              <input type="submit" class="btn btn-outline-dark" value="Войти">
                        </form>
                  </div>
            </div>
      </div>
{% endblock %}

users/templates/users/register.html
{% extends 'files/base.html' %}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
      <div class="col-6">
            <form method="post" enctype=multipart/form-data>
            <div class="card">
                  <div class="card-header">
                        Регистрация
                  </div>
                  {% if messages %}
                        <ul class="messages">
                        {% for message in messages|slice:":1" %}
                              <li>{{ message }}</li>
                        {% endfor %}
                        </ul>
                  {% endif %}
                  <div class="card-body">
                        <form method="post">
                              {%csrf_token%}
                              {{form.as_p}}
                              <input type="submit" class="btn btn-outline-dark" value="Регистрация">
                        </form>
                  </div>
            </div>
      </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'files/base.html' %}

{% block content %}
<a class="btn btn-outline-dark" href="{%url 'files:upload_list'%}" role="button">Назад</a>
      <div class="col-6">
            <form method="post" enctype=multipart/form-data>
            <div class="card">
                  <div class="card-header">
                        Профиль
                  </div>
                  <div class="card-body">
                        <form method="post">
                              {%csrf_token%}
                              {{form.as_p}}
                              <input type="submit" class="btn btn-outline-dark" value="Сохранить">
                        </form>
                  </div>
            </div>
      </div>
{% endblock %}